# Generated by Django 3.2.3 on 2021-06-02 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0002_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_name', models.CharField(max_length=120, unique=True)),
                ('price', models.IntegerField()),
                ('specs', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='images')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileapp.brand')),
            ],
        ),
    ]
